spring.application.name=korolev-engine
spring.jackson.deserialization.fail-on-null-for-primitives=false
spring.devtools.remote.proxy.port=8081
# Enable Demo Mode to pre-populate 1000+ Financial Loan Product Flags
korolev.demo-mode=false